[[section-building-block-view]]


== Building Block View

=== Whitebox Overall System
[plantuml, "level1", png]
----
Actor User
Component LoMap
Component Pod
Component PodProvider

Component MapBox as "MapBox API"

User -right-> LoMap: interacts with

User .right.> Pod: owns

LoMap <-right-> Pod: manages

LoMap --> MapBox: uses

PodProvider --> Pod: provides

----

Motivation::
The LoMap application lets the user add and manage personal places of interest around the world. Its structure is designed in an almost full decentralized way, ensuring user's privacy. This is achieved using PODs.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Block name| Description

|*User*
|It is the person who uses the application and who owns the Pod.

|*LoMap*
|It is the application that allows the user to manage his places.

|*Map API*
|It is the API that allows the user to visualize the places on a map and also allows the autocompleting function.


|*Pod*
|It is the personal data store of the user. It is used to store the places and the all the information about them.

|===


=== Level 2
[plantuml, "level2", png]
----

Actor User
Component LoMap {
    Component Frontend{
    Component Views{
        Component MyPlaces
        Component AddPlace
        Component Social
        Component Settings
        Component Profile
    }
        Component Solidapi
    }

}
Component Inrupt
Component Pod
Component MapBox as "OpenStreetMap API"

User --> Frontend: interacts with
Inrupt--> Pod: provides

User ..> Pod: owns
Solidapi <--> Pod: manages
Frontend--> MapBox: uses
Views <--> Solidapi: communicates

----
Motivation::
Inside LoMap, the Frontend is connected with the Solidapi to manage PODs.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Block name| Description

|*MyPlaces*
|Shows the user's saved places in a map and a list.

|*AddPlace*
|Lets the user add a new place selecting it on a map.

|*Social*
|Lets the user see the places of his friends.

|*Settings*
|Lets the user change the app settings.

|*Profile*
|Lets the user manage his profile information.

|*SolidApi*
|It is the API that allows the Frontend to communicate with the Pod.


|===
