[[section-building-block-view]]


== Building Block View

=== Whitebox Overall System
[plantuml, "level1", png]
----
Actor User
Component LoMap
Component Pod
Component Map as "Map API"
Component Database

User -right-> LoMap: interacts with

User .right.> Pod: owns

LoMap <-right-> Pod: transfers data

LoMap --> Map: uses

LoMap <--> Database: transfers data

----

Motivation::
The LoMap application lets the user add and manage personal places of interest around the world. Its structure is designed in an almost full decentralized way, ensuring user's privacy. This is achieved using PODs.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Block name| Description

|*User*
|It is the person who uses the application and who owns the Pod.

|*LoMap*
|It is the application that allows the user to manage his places.

|*Map API*
|It is the API that allows the user to visualize the places on a map and also allows the autocompleting function.

|*Database*
|It is the database that stores small information about the places to improve the app performance.

|*Pod*
|It is the personal data store of the user. It is used to store the places and the all the information about them.

|===

=== Level 2
[plantuml, "level2", png]
----
Actor User
Component LoMap {
    Component Frontend
    Component Backend

}
Component Pod
Component Map as "Map API"
Component Database

User -right-> Frontend: interacts with

User .right.> Pod: owns

Backend <-right-> Pod: transfers data

Frontend --> Map: uses

Backend <--> Database: transfers data

Frontend <--> Backend: communicates
----
Motivation::
Inside LoMap, the system is separated by the Frontend and the Backend.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Block name| Description

|*Frontend*
|It is the part of the application that the user interacts with, and that uses the map API.

|*Backend*
|It is the part of the application that manages the data and the communication with the database.

|===

=== Level 3
[plantuml, "level3", png]
----
Actor User
Component LoMap {
    Component Frontend{
    Component Views{
        Component MyPlaces
        Component AddPlace
        Component Social
        Component Settings
        Component Profile
    }
        Component FrontendAPI
    }
    Component Backend{
        Component RESTAPI
        Component Solid
    }

}
Component Pod
Component Map as "OpenStreetMap API"
Component Database

User --> Frontend: interacts with
User ..> Pod: owns
Solid <--> Pod: manages
RESTAPI <--> Database: manages
Frontend --> Map: uses
FrontendAPI <--> Backend: communicates
Views <--> FrontendAPI: communicates

----
Motivation::
Inside LoMap, the system is separated by the Frontend and the Backend.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Block name| Description

|*MyPlaces*
|Shows the user's saved places in a map and a list.

|*AddPlace*
|Lets the user add a new place selecting it on a map.

|*Social*
|Lets the user see the places of his friends.

|*Settings*
|Lets the user change the app settings.

|*Profile*
|Lets the user manage his profile information.

|*FrontendAPI*
|It is the API that allows the Frontend to communicate with the Backend.

|*RESTAPI*
|It is the API that allows the Backend to communicate with the Database.

|*Solid*
|It is the API that allows the Backend to communicate with the Pod.


|===